const types={
  LOGIN_SUCCESS:'LOGIN_SUCCESS',
  LOGIN_ERROR:'LOGIN_ERROR',
  REGISTER_SUCCESS:'REGISTER_SUCCESS',
  REGISTER_ERROR:'REGISTER_ERROR',
  LOGOUT_SUCCESS:'LOGOUT_SUCCESS'
}

export default types;